// lib/mcp/catalog.ts
import type { CatalogServer } from './types';
import type { SupabaseClient } from '@supabase/supabase-js';

export const CATALOG: CatalogServer[] = [
  // ─── oauth_app ────────────────────────────────────────────────────────────
  {
    slug: 'github',
    name: 'GitHub',
    description: 'Repos, issues, pull requests, code search.',
    author: 'modelcontextprotocol',
    category: 'dev',
    icon: '🐙',
    transport: 'http',
    install_ref: '@modelcontextprotocol/server-github',
    verified: true,
    config_schema: [
      {
        key: 'GITHUB_PERSONAL_ACCESS_TOKEN',
        label: 'GitHub Personal Access Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'search_repositories', description: 'Search repositories' },
      { name: 'create_issue', description: 'Create an issue' },
      { name: 'get_file_contents', description: 'Read a file' },
    ],
    meta: {
      authMethod: 'oauth_app',
      docsUrl: 'https://github.com/github/github-mcp-server',
      getKeyUrl: 'https://github.com/settings/tokens',
      steps: [
        'Operator registers an app in GitHub (Settings > Developer settings): a GitHub App for fine-grained user-to-server tokens, or an OAuth App for non-expiring tokens. Set the callback URL to Lucy\'s /connectors/github/callback.',
        'User clicks Connect: Lucy redirects to https://github.com/login/oauth/authorize with client_id, scope (repo read:org read:user), redirect_uri and state.',
        'Exchange the returned code at https://github.com/login/oauth/access_token for the access token (GitHub does NOT support DCR, so the app must be pre-registered).',
        'Connect to the hosted remote MCP at https://api.githubcopilot.com/mcp/ sending Authorization: Bearer <token>.',
        'Key-based fallback: user pastes a fine-grained or classic PAT from https://github.com/settings/tokens (scopes: repo, read:org, read:user).',
      ],
      oauth: {
        provider: 'github',
        remoteMcpUrl: 'https://api.githubcopilot.com/mcp/',
        authorizeUrl: 'https://github.com/login/oauth/authorize',
        tokenUrl: 'https://github.com/login/oauth/access_token',
        scopes: ['repo', 'read:org', 'read:user', 'user:email', 'gist', 'workflow'],
        dcr: false,
      },
    },
  },
  {
    slug: 'google-drive',
    name: 'Google Drive',
    description: 'Search and retrieve files from Google Drive and Docs.',
    category: 'cloud',
    icon: '📂',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'search_files', description: 'Search files in Google Drive' },
      { name: 'get_file_content', description: 'Read the content of a file' },
      { name: 'list_files', description: 'List files in a folder' },
    ],
    meta: {
      authMethod: 'oauth_app',
      docsUrl: 'https://developers.google.com/identity/protocols/oauth2/web-server',
      steps: [
        'Operator creates a Google Cloud project, enables the Drive API, and creates an OAuth 2.0 Web Client ID at https://console.cloud.google.com/apis/credentials with Lucy\'s callback URL.',
        'Configure the OAuth consent screen and add the Drive scopes (these are sensitive/restricted and need Google verification for production).',
        'User clicks Connect: Lucy redirects to https://accounts.google.com/o/oauth2/v2/auth with access_type=offline and prompt=consent.',
        'Exchange the code at https://oauth2.googleapis.com/token for access + refresh tokens; refresh as needed (access tokens last ~1h).',
      ],
      oauth: {
        provider: 'google-drive',
        authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        scopes: [
          'https://www.googleapis.com/auth/drive.readonly',
          'https://www.googleapis.com/auth/drive.file',
          'openid',
          'email',
          'profile',
        ],
        dcr: false,
      },
    },
  },
  {
    slug: 'gmail',
    name: 'Gmail',
    description: 'Search and read emails, create drafts in Gmail.',
    category: 'productivity',
    icon: '✉️',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'search_emails', description: 'Search emails in Gmail' },
      { name: 'get_email', description: 'Read a specific email' },
      { name: 'create_draft', description: 'Create an email draft' },
    ],
    meta: {
      authMethod: 'oauth_app',
      docsUrl: 'https://developers.google.com/identity/protocols/oauth2/web-server',
      steps: [
        'Operator creates/uses a Google Cloud project, enables the Gmail API, and creates an OAuth 2.0 Web Client ID at https://console.cloud.google.com/apis/credentials with Lucy\'s callback URL.',
        'Configure the consent screen and add the Gmail scopes (sensitive/restricted; need Google verification for production).',
        'User clicks Connect and authorizes via the Google consent screen (access_type=offline, prompt=consent).',
        'Exchange the code at https://oauth2.googleapis.com/token for access + refresh tokens; refresh as the ~1h access token expires.',
      ],
      oauth: {
        provider: 'gmail',
        authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        scopes: [
          'https://www.googleapis.com/auth/gmail.readonly',
          'https://www.googleapis.com/auth/gmail.compose',
          'openid',
          'email',
          'profile',
        ],
        dcr: false,
      },
    },
  },
  {
    slug: 'google-calendar',
    name: 'Google Calendar',
    description: 'Read and write events, availability, and Meet links.',
    category: 'productivity',
    icon: '📅',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_events', description: 'List calendar events' },
      { name: 'create_event', description: 'Create a calendar event' },
      { name: 'get_availability', description: 'Check availability for a time range' },
    ],
    meta: {
      authMethod: 'oauth_app',
      docsUrl: 'https://developers.google.com/identity/protocols/oauth2/web-server',
      steps: [
        'Operator creates/uses a Google Cloud project, enables the Calendar API, and creates an OAuth 2.0 Web Client ID at https://console.cloud.google.com/apis/credentials with Lucy\'s callback URL.',
        'Configure the consent screen and add the calendar scope.',
        'User clicks Connect and authorizes via the Google consent screen (access_type=offline, prompt=consent).',
        'Exchange the code at https://oauth2.googleapis.com/token for access + refresh tokens; refresh as needed.',
      ],
      oauth: {
        provider: 'google-calendar',
        authorizeUrl: 'https://accounts.google.com/o/oauth2/v2/auth',
        tokenUrl: 'https://oauth2.googleapis.com/token',
        scopes: [
          'https://www.googleapis.com/auth/calendar',
          'openid',
          'email',
          'profile',
        ],
        dcr: false,
      },
    },
  },
  {
    slug: 'microsoft-365',
    name: 'Microsoft 365',
    description: 'Outlook mail/calendar, OneDrive, Teams, and the full Microsoft Graph.',
    category: 'productivity',
    icon: '🪟',
    transport: 'http',
    install_ref: 'npx -y @softeria/ms-365-mcp-server',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_emails', description: 'List Outlook emails' },
      { name: 'list_calendar_events', description: 'List calendar events' },
      { name: 'list_files', description: 'List OneDrive/SharePoint files' },
    ],
    meta: {
      authMethod: 'oauth_app',
      docsUrl: 'https://github.com/softeria/ms-365-mcp-server',
      steps: [
        'In the Microsoft Entra admin center, register a new app (Identity > Applications > App registrations) with a Web redirect URI matching Lucy\'s OAuth callback; copy the Application (client) ID and Directory (tenant) ID, and create a client secret for the confidential flow.',
        'Under API permissions add Microsoft Graph DELEGATED permissions (Mail.ReadWrite, Mail.Send, Calendars.ReadWrite, Files.ReadWrite.All, Sites.ReadWrite.All, Chat.ReadWrite, Tasks.ReadWrite, User.Read) plus offline_access; grant admin consent if the tenant requires it.',
        'Point Lucy\'s Connect flow at https://login.microsoftonline.com/{tenant}/oauth2/v2.0/{authorize|token} (use \'common\', \'organizations\', or a tenant GUID) requesting the scopes above with PKCE.',
        'Run the MCP server (npx -y @softeria/ms-365-mcp-server) configured with your Entra client ID/secret/tenant, and pass the user\'s access token.',
      ],
      oauth: {
        provider: 'microsoft-365',
        authorizeUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
        tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        scopes: [
          'offline_access',
          'openid',
          'profile',
          'User.Read',
          'Mail.ReadWrite',
          'Mail.Send',
          'Calendars.ReadWrite',
          'Files.ReadWrite.All',
          'Sites.ReadWrite.All',
          'Tasks.ReadWrite',
          'Chat.ReadWrite',
          'OnlineMeetings.ReadWrite',
        ],
        dcr: false,
      },
    },
  },
  {
    slug: 'slack',
    name: 'Slack',
    description: 'Read & send messages, search channels.',
    category: 'messaging',
    icon: '💬',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-slack',
    verified: true,
    config_schema: [
      {
        key: 'SLACK_BOT_TOKEN',
        label: 'Slack Bot Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'post_message', description: 'Send a message' },
      { name: 'list_channels', description: 'List channels' },
    ],
    meta: {
      authMethod: 'oauth_app',
      docsUrl: 'https://docs.slack.dev/authentication/installing-with-oauth/',
      getKeyUrl: 'https://api.slack.com/apps',
      steps: [
        'Operator creates a Slack app at https://api.slack.com/apps, adds Bot Token Scopes (channels:read, chat:write, users:read, etc.) and sets the OAuth redirect URL to Lucy\'s callback.',
        'User clicks Connect: Lucy redirects to https://slack.com/oauth/v2/authorize with client_id, scope, redirect_uri and state (user scopes via user_scope).',
        'Exchange the returned code at https://slack.com/api/oauth.v2.access for the bot/user token (xoxb-/xoxp-).',
        'Store the token and use it as the bearer for the Slack MCP server. Key-based fallback: an admin pastes the Bot User OAuth Token from the app\'s OAuth & Permissions page.',
      ],
      oauth: {
        provider: 'slack',
        authorizeUrl: 'https://slack.com/oauth/v2/authorize',
        tokenUrl: 'https://slack.com/api/oauth.v2.access',
        scopes: [
          'channels:read',
          'channels:history',
          'chat:write',
          'users:read',
          'groups:read',
          'im:read',
          'files:read',
        ],
        dcr: false,
      },
    },
  },

  // ─── oauth_remote_mcp ─────────────────────────────────────────────────────
  {
    slug: 'notion',
    name: 'Notion',
    description: 'Pages, databases, search your workspace.',
    category: 'productivity',
    icon: '📝',
    transport: 'http',
    install_ref: '@notionhq/notion-mcp-server',
    verified: true,
    config_schema: [
      {
        key: 'NOTION_TOKEN',
        label: 'Notion Integration Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'search', description: 'Search pages' },
      { name: 'query_database', description: 'Query a database' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developers.notion.com/guides/mcp/get-started-with-mcp',
      getKeyUrl: 'https://www.notion.so/profile/integrations',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.notion.com/mcp.',
        'Lucy discovers OAuth metadata at /.well-known/oauth-authorization-server and self-registers via Dynamic Client Registration (no manual app needed).',
        'Run the OAuth 2.1 + PKCE flow; the user signs in to Notion and selects which workspace/pages to share.',
        'Store the access token (~1h) and refresh token; refresh as needed. Key-based fallback: an internal integration token from notion.so/profile/integrations.',
      ],
      oauth: {
        provider: 'notion',
        remoteMcpUrl: 'https://mcp.notion.com/mcp',
        authorizeUrl: 'https://mcp.notion.com/authorize',
        tokenUrl: 'https://mcp.notion.com/token',
        scopes: [],
        dcr: true,
      },
    },
  },
  {
    slug: 'linear',
    name: 'Linear',
    description: 'Issues, projects, cycles.',
    category: 'productivity',
    icon: '📐',
    transport: 'http',
    install_ref: 'npx mcp-remote https://mcp.linear.app/mcp',
    verified: true,
    config_schema: [
      {
        key: 'LINEAR_API_KEY',
        label: 'Linear API Key',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'list_issues', description: 'List issues' },
      { name: 'create_issue', description: 'Create an issue' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://linear.app/docs/mcp',
      getKeyUrl: 'https://linear.app/settings/account/security',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.linear.app/mcp.',
        'Lucy fetches OAuth metadata from /.well-known/oauth-authorization-server and self-registers via DCR (no manual app).',
        'Run OAuth 2.1 + PKCE; the user authorizes and access is scoped to what they can see in Linear.',
        'Key-based fallback: create a personal API key at https://linear.app/settings/account/security and pass it as Authorization: Bearer.',
      ],
      oauth: {
        provider: 'linear',
        remoteMcpUrl: 'https://mcp.linear.app/mcp',
        authorizeUrl: 'https://linear.app/oauth/authorize',
        tokenUrl: 'https://api.linear.app/oauth/token',
        scopes: ['read', 'write', 'issues:create', 'comments:create'],
        dcr: true,
      },
    },
  },
  {
    slug: 'atlassian',
    name: 'Atlassian (Jira + Confluence)',
    description: 'Jira issues, Confluence pages, and the full Atlassian suite via Rovo.',
    category: 'productivity',
    icon: '🗂️',
    transport: 'http',
    install_ref: 'npx mcp-remote https://mcp.atlassian.com/v1/mcp',
    verified: true,
    config_schema: [
      {
        key: 'ATLASSIAN_API_TOKEN',
        label: 'Atlassian API Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'search_issues', description: 'Search Jira issues' },
      { name: 'create_issue', description: 'Create a Jira issue' },
      { name: 'get_page', description: 'Retrieve a Confluence page' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://support.atlassian.com/atlassian-rovo-mcp-server/docs/getting-started-with-the-atlassian-remote-mcp-server/',
      getKeyUrl: 'https://id.atlassian.com/manage-profile/security/api-tokens',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.atlassian.com/v1/mcp (OAuth 2.1 endpoint).',
        'The server advertises OAuth metadata and supports DCR; run the OAuth 2.1 browser consent so the user approves their Jira/Confluence sites (include offline_access for a refresh token).',
        'Authorize at https://auth.atlassian.com/authorize and exchange the code at https://auth.atlassian.com/oauth/token.',
        'Key-based fallback: create an API token at https://id.atlassian.com/manage-profile/security/api-tokens and pass it as a bearer.',
      ],
      oauth: {
        provider: 'atlassian',
        remoteMcpUrl: 'https://mcp.atlassian.com/v1/mcp',
        authorizeUrl: 'https://auth.atlassian.com/authorize',
        tokenUrl: 'https://auth.atlassian.com/oauth/token',
        scopes: [
          'read:jira-work',
          'write:jira-work',
          'read:confluence-content.all',
          'write:page:confluence',
          'offline_access',
        ],
        dcr: true,
      },
    },
  },
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    description: 'DNS, Workers, R2, Zero Trust, and the full Cloudflare API.',
    category: 'cloud',
    icon: '🌥️',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_dns_records', description: 'List DNS records for a zone' },
      { name: 'deploy_worker', description: 'Deploy a Cloudflare Worker' },
      { name: 'list_r2_buckets', description: 'List R2 storage buckets' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/',
      getKeyUrl: 'https://dash.cloudflare.com/profile/api-tokens',
      steps: [
        'On Lucy\'s /connectors page click Connect on Cloudflare and pick which Cloudflare MCP server URL to use (default: the API server at https://mcp.cloudflare.com/mcp; others include observability., radar., bindings., browser.).',
        'Lucy auto-discovers OAuth metadata at https://<host>/.well-known/oauth-authorization-server and self-registers via DCR (RFC 7591) — no manual app setup.',
        'You are redirected to Cloudflare to sign in and approve account/zone permissions on the consent screen.',
        'Cloudflare redirects back with a PKCE S256 code; Lucy exchanges it at the /token endpoint for access + refresh tokens, stored encrypted per-user (auto-refresh).',
      ],
      oauth: {
        provider: 'cloudflare',
        remoteMcpUrl: 'https://mcp.cloudflare.com/mcp',
        authorizeUrl: 'https://mcp.cloudflare.com/authorize',
        tokenUrl: 'https://mcp.cloudflare.com/token',
        scopes: [],
        dcr: true,
      },
    },
  },
  {
    slug: 'sentry',
    name: 'Sentry',
    description: 'Errors, issues, and performance data.',
    category: 'dev',
    icon: '🐞',
    transport: 'http',
    install_ref: 'npx -y @sentry/mcp-server@latest',
    verified: true,
    config_schema: [
      {
        key: 'SENTRY_ACCESS_TOKEN',
        label: 'Sentry Auth Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'list_issues', description: 'List issues' },
      { name: 'get_issue', description: 'Get an issue' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://docs.sentry.io/product/sentry-mcp/',
      getKeyUrl: 'https://sentry.io/settings/account/api/auth-tokens/',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.sentry.dev/mcp.',
        'The server advertises OAuth metadata at /.well-known/oauth-authorization-server and supports DCR — no manual app registration.',
        'Run the OAuth flow: the user signs in with their Sentry org and grants access on the consent screen.',
        'Key/self-hosted fallback: create an auth token at https://sentry.io/settings/account/api/auth-tokens/ (scopes org:read, project:read, event:read) and run the @sentry/mcp-server stdio variant (SENTRY_ACCESS_TOKEN, plus SENTRY_HOST for self-hosted).',
      ],
      oauth: {
        provider: 'sentry',
        remoteMcpUrl: 'https://mcp.sentry.dev/mcp',
        authorizeUrl: 'https://mcp.sentry.dev/oauth/authorize',
        tokenUrl: 'https://mcp.sentry.dev/oauth/token',
        scopes: [],
        dcr: true,
      },
    },
  },
  {
    slug: 'supabase',
    name: 'Supabase',
    description: 'Query tables, run SQL, manage your project.',
    category: 'data',
    icon: '⚡',
    transport: 'http',
    install_ref: 'npx -y @supabase/mcp-server-supabase@latest',
    verified: true,
    config_schema: [
      {
        key: 'SUPABASE_ACCESS_TOKEN',
        label: 'Supabase Access Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'execute_sql', description: 'Run SQL' },
      { name: 'list_tables', description: 'List tables' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://supabase.com/docs/guides/getting-started/mcp',
      getKeyUrl: 'https://supabase.com/dashboard/account/tokens',
      steps: [
        'Point Lucy\'s Connect button at the hosted Supabase MCP and run the OAuth flow (the hosted MCP supports Dynamic Client Registration); sign in to Supabase and approve access.',
        'Scope access to a single project and prefer read-only where possible.',
        'Key-based fallback: generate a personal access token at https://supabase.com/dashboard/account/tokens.',
        'For the stdio path, run @supabase/mcp-server-supabase with --read-only --project-ref=YOUR_REF and SUPABASE_ACCESS_TOKEN.',
      ],
      oauth: {
        provider: 'supabase',
        remoteMcpUrl: 'https://mcp.supabase.com/mcp',
        authorizeUrl: 'https://api.supabase.com/v1/oauth/authorize',
        tokenUrl: 'https://api.supabase.com/v1/oauth/token',
        scopes: [],
        dcr: true,
      },
    },
  },
  {
    slug: 'gitlab',
    name: 'GitLab',
    description: 'Projects, issues, merge requests, files.',
    category: 'dev',
    icon: '🦊',
    transport: 'http',
    install_ref: '@modelcontextprotocol/server-gitlab',
    verified: true,
    config_schema: [
      {
        key: 'GITLAB_PERSONAL_ACCESS_TOKEN',
        label: 'GitLab Personal Access Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'search_repositories', description: 'Search projects' },
      { name: 'create_issue', description: 'Create an issue' },
      { name: 'create_merge_request', description: 'Open a merge request' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://docs.gitlab.com/user/gitlab_duo/model_context_protocol/mcp_server/',
      getKeyUrl: 'https://gitlab.com/-/user_settings/personal_access_tokens',
      steps: [
        'Point Lucy\'s Connect button at the GitLab MCP server URL (https://gitlab.com/api/v4/mcp for GitLab.com; for self-hosted use https://your-host/api/v4/mcp).',
        'Authenticate via GitLab OAuth and approve the requested access.',
        'Key-based fallback: create a personal access token at https://gitlab.com/-/user_settings/personal_access_tokens with the api (or read_api/read_repository) scope and pass it as a bearer.',
        'For self-hosted GitLab, also set GITLAB_API_URL to https://your-gitlab-host/api/v4.',
      ],
      oauth: {
        provider: 'gitlab',
        remoteMcpUrl: 'https://gitlab.com/api/v4/mcp',
        authorizeUrl: 'https://gitlab.com/oauth/authorize',
        tokenUrl: 'https://gitlab.com/oauth/token',
        scopes: ['api', 'read_api', 'read_user'],
        dcr: true,
      },
    },
  },
  {
    slug: 'stripe',
    name: 'Stripe',
    description: 'Customers, payments, invoices.',
    category: 'payments',
    icon: '💳',
    transport: 'http',
    install_ref: 'npx -y @stripe/mcp',
    verified: true,
    config_schema: [
      {
        key: 'STRIPE_SECRET_KEY',
        label: 'Stripe Secret Key',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'list_customers', description: 'List customers' },
      { name: 'create_payment_link', description: 'Create a payment link' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://docs.stripe.com/mcp',
      getKeyUrl: 'https://dashboard.stripe.com/apikeys',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.stripe.com and start the Stripe OAuth flow (preferred, most secure).',
        'Sign in to Stripe and authorize access to your account.',
        'Key-based fallback: create a RESTRICTED API key at https://dashboard.stripe.com/apikeys scoped to least privilege and pass it as Authorization: Bearer (Connect platforms add the Stripe-Account header).',
        'Test with a test-mode key (sk_test_/rk_test_) before going live.',
      ],
      oauth: {
        provider: 'stripe',
        remoteMcpUrl: 'https://mcp.stripe.com',
        authorizeUrl: 'https://mcp.stripe.com/authorize',
        tokenUrl: 'https://mcp.stripe.com/token',
        scopes: [],
        dcr: true,
      },
    },
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    description: 'Invoices, orders, payments, and subscriptions via PayPal.',
    category: 'payments',
    icon: '🅿️',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_invoices', description: 'List PayPal invoices' },
      { name: 'get_order', description: 'Retrieve a PayPal order' },
      { name: 'list_transactions', description: 'List recent transactions' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://docs.paypal.ai/developer/tools/ai/mcp-quickstart',
      getKeyUrl: 'https://developer.paypal.com/dashboard/applications',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.paypal.com/mcp (production) or https://mcp.sandbox.paypal.com (sandbox).',
        'Click Connect; the user logs in to PayPal and authorizes the requested permissions (the client discovers endpoints via /.well-known/oauth-authorization-server).',
        'Token exchange uses https://api-m.paypal.com/v1/oauth2/token; the response is a bearer token with expiry.',
        'Alternatively connect with PayPal client credentials (client ID/secret) from the PayPal Developer Dashboard. Start in sandbox, then switch to production.',
      ],
      oauth: {
        provider: 'paypal',
        remoteMcpUrl: 'https://mcp.paypal.com/mcp',
        authorizeUrl: 'https://www.paypal.com/signin/authorize',
        tokenUrl: 'https://api-m.paypal.com/v1/oauth2/token',
        scopes: [
          'openid',
          'https://uri.paypal.com/services/invoicing',
          'https://uri.paypal.com/services/payments/payment',
        ],
        dcr: true,
      },
    },
  },
  {
    slug: 'square',
    name: 'Square',
    description: 'Payments, orders, customers, catalog, and inventory via Square.',
    category: 'payments',
    icon: '⬛',
    transport: 'http',
    verified: true,
    config_schema: [
      {
        key: 'SQUARE_ACCESS_TOKEN',
        label: 'Square Access Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'list_payments', description: 'List Square payments' },
      { name: 'list_orders', description: 'List orders' },
      { name: 'search_customers', description: 'Search customers' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developer.squareup.com/docs/mcp',
      getKeyUrl: 'https://developer.squareup.com/apps',
      steps: [
        'Point Lucy\'s Connect button at the hosted remote server https://mcp.squareup.com/sse, which supports OAuth login with granular scopes.',
        'Sign in with your Square account and authorize only the scopes needed; authorize at https://connect.squareup.com/oauth2/authorize and exchange the code at /oauth2/token.',
        'Key-based fallback: paste a Square access token from the Developer Dashboard (sandbox tokens for testing).',
        'Operators who need a registered app create one at https://developer.squareup.com/apps to get the Application ID + OAuth secret.',
      ],
      oauth: {
        provider: 'square',
        remoteMcpUrl: 'https://mcp.squareup.com/sse',
        authorizeUrl: 'https://connect.squareup.com/oauth2/authorize',
        tokenUrl: 'https://connect.squareup.com/oauth2/token',
        scopes: [
          'PAYMENTS_READ',
          'ORDERS_READ',
          'CUSTOMERS_READ',
          'ITEMS_READ',
          'MERCHANT_PROFILE_READ',
        ],
        dcr: true,
      },
    },
  },
  {
    slug: 'hubspot',
    name: 'HubSpot',
    description: 'CRM contacts, companies, deals, and activities via HubSpot.',
    category: 'crm',
    icon: '🟠',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'search_contacts', description: 'Search CRM contacts' },
      { name: 'get_deal', description: 'Retrieve a deal record' },
      { name: 'create_contact', description: 'Create a new contact' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developers.hubspot.com/docs/apps/developer-platform/build-apps/integrate-with-the-remote-hubspot-mcp-server',
      steps: [
        'Operator creates an \'MCP auth app\' in HubSpot (Development > MCP Auth Apps > Create) at https://app.hubspot.com/l/mcp-auth-apps/ to get client_id/client_secret and set the redirect URL.',
        'Point Lucy\'s Connect button at https://mcp.hubspot.com and run OAuth 2.1 with PKCE (required).',
        'Authorize at https://mcp.hubspot.com/oauth/authorize and exchange the code at https://mcp.hubspot.com/oauth/v3/token.',
        'The endpoint requires a USER-level OAuth token (private-app/server-to-server tokens are rejected); access maps to the authorized user\'s permissions.',
      ],
      oauth: {
        provider: 'hubspot',
        remoteMcpUrl: 'https://mcp.hubspot.com',
        authorizeUrl: 'https://mcp.hubspot.com/oauth/authorize',
        tokenUrl: 'https://mcp.hubspot.com/oauth/v3/token',
        scopes: [
          'crm.objects.contacts.read',
          'crm.objects.companies.read',
          'crm.objects.deals.read',
          'crm.objects.contacts.write',
        ],
        dcr: false,
      },
    },
  },
  {
    slug: 'intercom',
    name: 'Intercom',
    description: 'Conversations, contacts, companies, and Help Center articles.',
    category: 'messaging',
    icon: '💬',
    transport: 'http',
    install_ref: 'npx mcp-remote https://mcp.intercom.com/mcp',
    verified: true,
    config_schema: [
      {
        key: 'INTERCOM_ACCESS_TOKEN',
        label: 'Intercom Access Token',
        type: 'secret',
        required: false,
        help: 'Optional — paste a token now, or use Connect (coming soon).',
      },
    ],
    tools: [
      { name: 'list_conversations', description: 'List Intercom conversations' },
      { name: 'search_contacts', description: 'Search contacts' },
      { name: 'get_article', description: 'Retrieve a Help Center article' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developers.intercom.com/docs/guides/mcp',
      getKeyUrl: 'https://app.intercom.com/a/apps/_/developer-hub',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.intercom.com/mcp.',
        'Run the OAuth 2.1 flow (recommended); the user signs in to their Intercom workspace and grants the read scopes.',
        'Key-based fallback: obtain an access token from the Intercom Developer Hub and pass it as Authorization: Bearer.',
        'US-hosted Intercom workspaces only at present; legacy SSE endpoint at https://mcp.intercom.com/sse.',
      ],
      oauth: {
        provider: 'intercom',
        remoteMcpUrl: 'https://mcp.intercom.com/mcp',
        authorizeUrl: 'https://app.intercom.com/oauth',
        tokenUrl: 'https://api.intercom.io/auth/eagle/token',
        scopes: [],
        dcr: true,
      },
    },
  },
  {
    slug: 'asana',
    name: 'Asana',
    description: 'Tasks, projects, portfolios, and workspaces via Asana.',
    category: 'productivity',
    icon: '🎯',
    transport: 'http',
    install_ref: 'npx mcp-remote https://mcp.asana.com/v2/mcp',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_tasks', description: 'List tasks in a project' },
      { name: 'create_task', description: 'Create a new task' },
      { name: 'get_project', description: 'Retrieve a project' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developers.asana.com/docs/using-asanas-mcp-server',
      steps: [
        'Operator creates an app in the Asana Developer Console (https://app.asana.com/0/developer-console) to get client_id/client_secret — Asana V2 MCP does NOT support DCR, so pre-registration is required.',
        'Point Lucy\'s Connect button at https://mcp.asana.com/v2/mcp and run the OAuth flow; the user signs in and authorizes.',
        'Do NOT send a \'scope\' parameter — Asana MCP apps use no scopes and reject scope params; access is governed by the user\'s Asana permissions.',
        'Authorize at https://app.asana.com/-/oauth_authorize and exchange the code at https://app.asana.com/-/oauth_token (MCP-issued tokens only work against the MCP server).',
      ],
      oauth: {
        provider: 'asana',
        remoteMcpUrl: 'https://mcp.asana.com/v2/mcp',
        authorizeUrl: 'https://app.asana.com/-/oauth_authorize',
        tokenUrl: 'https://app.asana.com/-/oauth_token',
        scopes: [],
        dcr: false,
      },
    },
  },
  {
    slug: 'box',
    name: 'Box',
    description: 'Files, folders, Box AI multi-file query, and Doc Gen.',
    category: 'cloud',
    icon: '📦',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'search_files', description: 'Search files in Box' },
      { name: 'get_file', description: 'Retrieve a file from Box' },
      { name: 'list_folder', description: 'List folder contents' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developer.box.com/guides/box-mcp/setup',
      steps: [
        'Preferred: a Box admin enables the Box MCP server from the Admin Console (Integrations > filter MCP), which provisions client_id/client_secret.',
        'Alternative: the operator creates an OAuth 2.0 app in the Box Developer Console (https://app.box.com/developers/console) with the redirect URI and scopes root_readwrite, ai.readwrite, docgen.readwrite.',
        'Point Lucy\'s Connect button at https://mcp.box.com and run the OAuth flow: authorize at https://account.box.com/api/oauth2/authorize, exchange the code at https://api.box.com/oauth2/token.',
        'Tools then operate within the user\'s Box permissions (OAuth metadata at account.box.com/.well-known/oauth-authorization-server).',
      ],
      oauth: {
        provider: 'box',
        remoteMcpUrl: 'https://mcp.box.com',
        authorizeUrl: 'https://account.box.com/api/oauth2/authorize',
        tokenUrl: 'https://api.box.com/oauth2/token',
        scopes: ['root_readwrite', 'ai.readwrite', 'docgen.readwrite'],
        dcr: false,
      },
    },
  },
  {
    slug: 'canva',
    name: 'Canva',
    description: 'Designs, brand templates, assets, and exports via Canva AI.',
    category: 'productivity',
    icon: '🎨',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_designs', description: 'List Canva designs' },
      { name: 'create_design', description: 'Create a new design from a template' },
      { name: 'export_design', description: 'Export a design to PDF or image' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://www.canva.com/help/mcp-agent-setup/',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.canva.com/mcp.',
        'Click Connect; the user is prompted to log in and allow access to Canva.',
        'Sign in to Canva and authorize the AI assistant (OAuth Authorization Code + PKCE).',
        'After \'authorization successful\' the user is redirected back; the connector is active (access tokens last ~4h with refresh).',
      ],
      oauth: {
        provider: 'canva',
        remoteMcpUrl: 'https://mcp.canva.com/mcp',
        authorizeUrl: 'https://www.canva.com/api/oauth/authorize',
        tokenUrl: 'https://api.canva.com/rest/v1/oauth/token',
        scopes: ['design:content:read', 'design:content:write', 'asset:read', 'asset:write'],
        dcr: true,
      },
    },
  },
  {
    slug: 'figma',
    name: 'Figma',
    description: 'Design files, frames, and Dev Mode code generation.',
    category: 'productivity',
    icon: '🖼️',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'get_file', description: 'Retrieve a Figma design file' },
      { name: 'list_components', description: 'List components in a file' },
      { name: 'get_dev_resources', description: 'Get Dev Mode code snippets for a frame' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://developers.figma.com/docs/figma-mcp-server/remote-server-installation/',
      getKeyUrl: 'https://www.figma.com/developers/api#access-tokens',
      steps: [
        'Point Lucy\'s Connect button at https://mcp.figma.com/mcp.',
        'Click Connect to start Figma\'s OAuth flow.',
        'Sign in to Figma and authorize access to your files.',
        'Connector becomes active (full capabilities require a Figma seat with Dev/Full access).',
      ],
      oauth: {
        provider: 'figma',
        remoteMcpUrl: 'https://mcp.figma.com/mcp',
        authorizeUrl: 'https://www.figma.com/oauth',
        tokenUrl: 'https://api.figma.com/v1/oauth/token',
        scopes: ['files:read'],
        dcr: true,
      },
    },
  },
  {
    slug: 'zapier',
    name: 'Zapier',
    description: '8,000+ apps and actions exposed as MCP tools via Zapier.',
    category: 'productivity',
    icon: '⚡',
    transport: 'http',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_actions', description: 'List enabled Zapier actions' },
      { name: 'run_action', description: 'Execute a Zapier action' },
      { name: 'search_apps', description: 'Search available Zapier apps' },
    ],
    meta: {
      authMethod: 'oauth_remote_mcp',
      docsUrl: 'https://help.zapier.com/hc/en-us/articles/36265392843917-Use-Zapier-MCP-with-your-client',
      getKeyUrl: 'https://mcp.zapier.com/',
      steps: [
        'The user builds an MCP server config at https://mcp.zapier.com/ (choosing which Zapier actions/apps to expose) and gets a personal server URL.',
        'Point Lucy at the Zapier MCP endpoint (https://mcp.zapier.com/api/v1/mcp).',
        'Connecting initiates OAuth 2.1 + DCR — no API key setup required; Zapier handles the underlying app credentials.',
        'Alternatively pass the per-user token directly as Authorization: Bearer. Available tools are determined by the actions the user enabled.',
      ],
      oauth: {
        provider: 'zapier',
        remoteMcpUrl: 'https://mcp.zapier.com/api/v1/mcp',
        authorizeUrl: 'https://mcp.zapier.com/oauth/authorize',
        tokenUrl: 'https://mcp.zapier.com/oauth/token',
        scopes: [],
        dcr: true,
      },
    },
  },

  // ─── api_key ──────────────────────────────────────────────────────────────
  {
    slug: 'plaid',
    name: 'Plaid',
    description: 'Dashboard data — items, institutions, logs, and analytics via Plaid.',
    category: 'data',
    icon: '🏦',
    transport: 'http',
    verified: true,
    config_schema: [
      {
        key: 'PLAID_CLIENT_ID',
        label: 'Plaid Client ID',
        type: 'secret',
        required: true,
      },
      {
        key: 'PLAID_SECRET',
        label: 'Plaid Secret',
        type: 'secret',
        required: true,
      },
    ],
    tools: [
      { name: 'list_items', description: 'List connected Plaid items' },
      { name: 'get_institution', description: 'Get institution details' },
      { name: 'get_account_status', description: 'Get account connection status' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://plaid.com/docs/resources/mcp/',
      getKeyUrl: 'https://dashboard.plaid.com/developers/keys',
      steps: [
        'Get your client_id and secret from the Plaid Dashboard (Developers > Keys, https://dashboard.plaid.com/developers/keys).',
        'Mint an access token via POST https://production.plaid.com/oauth/token with grant_type=client_credentials and scope=mcp:dashboard (machine-to-machine, not a user OAuth flow).',
        'Point Lucy at https://api.dashboard.plaid.com/mcp/ and send the token as Authorization: Bearer.',
        'Tokens expire after 15 minutes; re-mint (or use the refresh_token) before each session. On 401, mint a fresh token.',
      ],
    },
  },
  {
    slug: 'apollo',
    name: 'Apollo',
    description: 'Sales intelligence: contact/company search, enrichment, and sequences.',
    category: 'crm',
    icon: '🚀',
    transport: 'stdio',
    verified: false,
    config_schema: [
      {
        key: 'APOLLO_API_KEY',
        label: 'Apollo API Key',
        type: 'secret',
        required: true,
        help: 'Create at developer.apollo.io/keys (admin profile required).',
      },
    ],
    tools: [
      { name: 'search_people', description: 'Search people in Apollo' },
      { name: 'enrich_contact', description: 'Enrich a contact with Apollo data' },
      { name: 'search_organizations', description: 'Search companies' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://docs.apollo.io/docs/create-api-key',
      getKeyUrl: 'https://developer.apollo.io/keys#/',
      steps: [
        'In Apollo go to Settings > Integrations > API Keys (direct: developer.apollo.io/keys). You need an admin permission profile to create keys.',
        'Click Create new key, enter a name and description.',
        'Select the API endpoints the key may access, or toggle \'Set as master key\' to grant all endpoints.',
        'Click Create API key, copy it, and paste it into Lucy\'s Apollo connector (sent as an X-Api-Key/Bearer header against api.apollo.io).',
      ],
    },
  },
  {
    slug: 'wordpress',
    name: 'WordPress',
    description: 'CRUD posts, pages, media, categories, and settings on a self-hosted site.',
    category: 'productivity',
    icon: '📰',
    transport: 'stdio',
    install_ref: 'npx @automattic/mcp-wordpress-remote',
    verified: false,
    config_schema: [
      {
        key: 'WP_API_URL',
        label: 'WordPress REST API URL',
        type: 'text',
        required: true,
        help: 'https://YOUR-SITE.com/wp-json',
      },
      {
        key: 'WP_API_USERNAME',
        label: 'WordPress Username',
        type: 'text',
        required: true,
      },
      {
        key: 'WP_API_PASSWORD',
        label: 'Application Password',
        type: 'secret',
        required: true,
        help: 'Application Password from wp-admin > Users > Profile.',
      },
    ],
    tools: [
      { name: 'list_posts', description: 'List WordPress posts' },
      { name: 'create_post', description: 'Create or update a post' },
      { name: 'upload_media', description: 'Upload a media file' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://developer.wordpress.org/advanced-administration/security/application-passwords/',
      getKeyUrl: 'https://YOUR-SITE.com/wp-admin/profile.php',
      steps: [
        'Install and activate Automattic\'s WordPress MCP plugin (or the WordPress/mcp-adapter package) on the site and enable it under Settings > WordPress MCP. The site must be served over HTTPS.',
        'Create an Application Password: in wp-admin go to Users > Profile (profile.php), scroll to \'Application Passwords\', name it (e.g. \'Lucy MCP\') and click Add New.',
        'Copy the generated password immediately (shown once) — it is used with your WordPress username via HTTP Basic Auth.',
        'Configure the connector: WP_API_URL = https://YOUR-SITE.com/wp-json/..., WP_API_USERNAME = your WP username, WP_API_PASSWORD = the Application Password (set OAUTH_ENABLED=false to use App Passwords).',
      ],
    },
  },
  {
    slug: 'airtable',
    name: 'Airtable',
    description: 'Read & write bases, tables, records.',
    category: 'data',
    icon: '🗂️',
    transport: 'stdio',
    install_ref: 'airtable-mcp-server',
    verified: false,
    config_schema: [
      {
        key: 'AIRTABLE_API_KEY',
        label: 'Airtable Personal Access Token',
        type: 'secret',
        required: true,
        help: 'Create a scoped PAT at airtable.com/create/tokens.',
      },
    ],
    tools: [
      { name: 'list_records', description: 'List records' },
      { name: 'create_record', description: 'Create a record' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://airtable.com/developers/web/guides/personal-access-tokens',
      getKeyUrl: 'https://airtable.com/create/tokens',
      steps: [
        'Go to the Airtable tokens page at https://airtable.com/create/tokens and click \'Create new token\'.',
        'Add the scopes you need: schema.bases:read and data.records:read (add the :write variants to allow edits).',
        'Under \'Access\', add the specific bases (or workspaces) the token may reach.',
        'Click \'Create token\', copy it (shown once), and paste it into Lucy as AIRTABLE_API_KEY.',
      ],
    },
  },
  {
    slug: 'brave-search',
    name: 'Brave Search',
    description: 'Web & local search for the AI.',
    category: 'search',
    icon: '🔎',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-brave-search',
    verified: true,
    config_schema: [
      {
        key: 'BRAVE_API_KEY',
        label: 'Brave Search API Key',
        type: 'secret',
        required: true,
        help: 'Subscribe to a plan first, then generate at api-dashboard.search.brave.com/app/keys.',
      },
    ],
    tools: [
      { name: 'brave_web_search', description: 'Web search' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://api-dashboard.search.brave.com/documentation/guides/authentication',
      getKeyUrl: 'https://api-dashboard.search.brave.com/app/keys',
      steps: [
        'Register at https://api-dashboard.search.brave.com/register and verify your email.',
        'Subscribe to a plan (the Free \'Data for Search\' tier allows ~2,000 requests/month) — a key cannot be created until a plan is active.',
        'Go to \'API Keys\' (https://api-dashboard.search.brave.com/app/keys) and generate a new key.',
        'Copy the key and paste it into Lucy as BRAVE_API_KEY.',
      ],
    },
  },
  {
    slug: 'exa',
    name: 'Exa Search',
    description: 'Neural web search built for AI.',
    category: 'search',
    icon: '🔭',
    transport: 'stdio',
    install_ref: 'npx -y exa-mcp-server',
    verified: true,
    config_schema: [
      {
        key: 'EXA_API_KEY',
        label: 'Exa API Key',
        type: 'secret',
        required: true,
        help: 'Create at dashboard.exa.ai/api-keys.',
      },
    ],
    tools: [
      { name: 'web_search', description: 'Search the web' },
      { name: 'find_similar', description: 'Find similar pages' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://docs.exa.ai/reference/quickstart',
      getKeyUrl: 'https://dashboard.exa.ai/api-keys',
      steps: [
        'Sign in at https://dashboard.exa.ai and open the API Keys page (https://dashboard.exa.ai/api-keys).',
        'Click \'+ Create new key\' and give it a reference name.',
        'Copy the generated key.',
        'Paste it into Lucy as EXA_API_KEY.',
      ],
    },
  },
  {
    slug: 'firecrawl',
    name: 'Firecrawl',
    description: 'Scrape and crawl websites into clean markdown.',
    category: 'search',
    icon: '🔥',
    transport: 'stdio',
    install_ref: 'npx -y firecrawl-mcp',
    verified: true,
    config_schema: [
      {
        key: 'FIRECRAWL_API_KEY',
        label: 'Firecrawl API Key',
        type: 'secret',
        required: true,
        help: 'Create at firecrawl.dev/app/api-keys (fc- prefix).',
      },
    ],
    tools: [
      { name: 'firecrawl_scrape', description: 'Scrape a page' },
      { name: 'firecrawl_crawl', description: 'Crawl a site' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://docs.firecrawl.dev/mcp-server',
      getKeyUrl: 'https://www.firecrawl.dev/app/api-keys',
      steps: [
        'Sign up / log in at https://www.firecrawl.dev.',
        'Open the API Keys page (https://www.firecrawl.dev/app/api-keys) from the dashboard.',
        'Create / copy your key (it starts with the fc- prefix; shown once).',
        'Paste it into Lucy as FIRECRAWL_API_KEY.',
      ],
    },
  },
  {
    slug: 'tavily',
    name: 'Tavily',
    description: 'Search and extract optimised for LLMs.',
    category: 'search',
    icon: '🌊',
    transport: 'stdio',
    install_ref: 'npx -y tavily-mcp',
    verified: true,
    config_schema: [
      {
        key: 'TAVILY_API_KEY',
        label: 'Tavily API Key',
        type: 'secret',
        required: true,
        help: 'Get your tvly- key from app.tavily.com/home.',
      },
    ],
    tools: [
      { name: 'tavily_search', description: 'Search the web' },
      { name: 'tavily_extract', description: 'Extract page content' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://docs.tavily.com/documentation/mcp',
      getKeyUrl: 'https://app.tavily.com/home',
      steps: [
        'Create a free account / sign in at https://app.tavily.com/home.',
        'Your API key (prefixed tvly-) is shown on the dashboard home; create a new key if needed.',
        'Copy the key.',
        'Paste it into Lucy as TAVILY_API_KEY.',
      ],
    },
  },
  {
    slug: 'google-maps',
    name: 'Google Maps',
    description: 'Geocoding, places, directions, distance.',
    category: 'search',
    icon: '🗺️',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-google-maps',
    verified: true,
    config_schema: [
      {
        key: 'GOOGLE_MAPS_API_KEY',
        label: 'Google Maps API Key',
        type: 'secret',
        required: true,
        help: 'Enable Maps APIs and create a key at console.cloud.google.com/google/maps-apis/credentials.',
      },
    ],
    tools: [
      { name: 'maps_geocode', description: 'Geocode an address' },
      { name: 'maps_directions', description: 'Get directions' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://developers.google.com/maps/documentation/places/web-service/get-api-key',
      getKeyUrl: 'https://console.cloud.google.com/google/maps-apis/credentials',
      steps: [
        'In Google Cloud Console create or select a project and attach a billing account (required for Maps API calls).',
        'Enable the needed APIs (Places API (New), Geocoding API, Routes API) under Maps APIs.',
        'Open Maps APIs > Credentials (https://console.cloud.google.com/google/maps-apis/credentials) and click \'Create credentials\' > \'API key\'.',
        'Copy the key (optionally restrict it to those APIs) and paste it into Lucy as GOOGLE_MAPS_API_KEY.',
      ],
    },
  },
  {
    slug: 'discord',
    name: 'Discord',
    description: 'Read & send messages in your Discord server.',
    category: 'messaging',
    icon: '🎮',
    transport: 'stdio',
    install_ref: 'mcp-discord',
    verified: false,
    config_schema: [
      {
        key: 'DISCORD_TOKEN',
        label: 'Discord Bot Token',
        type: 'secret',
        required: true,
        help: 'Create a bot at discord.com/developers/applications and copy the token.',
      },
    ],
    tools: [
      { name: 'send_message', description: 'Send a message' },
      { name: 'read_messages', description: 'Read channel messages' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://discord.com/developers/docs/intro',
      getKeyUrl: 'https://discord.com/developers/applications',
      steps: [
        'Go to the Discord Developer Portal (https://discord.com/developers/applications) and click \'New Application\'.',
        'Open the \'Bot\' tab, click \'Reset Token\', and copy the bot token (shown once).',
        'Under Privileged Gateway Intents enable \'Message Content Intent\' (and \'Server Members Intent\' if needed), then save.',
        'Use the OAuth2 URL generator to invite the bot to your server, then paste the token into Lucy as DISCORD_TOKEN.',
      ],
    },
  },
  {
    slug: 'apify',
    name: 'Apify',
    description: 'Actors and the Apify Store — web scraping and data extraction at scale.',
    category: 'data',
    icon: '🕷️',
    transport: 'stdio',
    install_ref: 'npx -y @apify/actors-mcp-server',
    verified: true,
    config_schema: [
      {
        key: 'APIFY_TOKEN',
        label: 'Apify API Token',
        type: 'secret',
        required: true,
        help: 'Copy your Personal API token from console.apify.com/settings/integrations.',
      },
    ],
    tools: [
      { name: 'run_actor', description: 'Run an Apify Actor' },
      { name: 'get_dataset_items', description: 'Retrieve results from a dataset' },
      { name: 'search_store', description: 'Search the Apify Actor Store' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://docs.apify.com/platform/integrations/mcp',
      getKeyUrl: 'https://console.apify.com/settings/integrations',
      steps: [
        'Sign in at https://console.apify.com and open Settings > Integrations (https://console.apify.com/settings/integrations).',
        'Copy your Personal API token (or create a new one).',
        'Paste it into Lucy as APIFY_TOKEN; the stdio server runs via npx -y @apify/actors-mcp-server.',
        'Alternatively connect to the hosted remote MCP at https://mcp.apify.com, which also supports the API token as a bearer.',
      ],
    },
  },

  {
    slug: 'n8n',
    name: 'n8n',
    description: 'Build, manage, and run your n8n workflows and automations.',
    category: 'productivity',
    icon: '🔁',
    transport: 'stdio',
    install_ref: 'n8n-mcp',
    verified: false,
    config_schema: [
      { key: 'N8N_API_URL', label: 'n8n API URL', type: 'text', required: true, help: 'e.g. https://your-n8n-host/api/v1' },
      { key: 'N8N_API_KEY', label: 'n8n API Key', type: 'secret', required: true, help: 'Settings > n8n API > Create an API key.' },
    ],
    tools: [
      { name: 'list_workflows', description: 'List n8n workflows' },
      { name: 'execute_workflow', description: 'Run a workflow' },
      { name: 'get_workflow', description: 'Get a workflow definition' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://github.com/czlonkowski/n8n-mcp',
      getKeyUrl: 'https://docs.n8n.io/api/authentication/',
      steps: [
        'In your n8n instance open Settings > n8n API and click "Create an API key"; copy it.',
        'Note your n8n API base URL (e.g. https://your-n8n-host/api/v1).',
        'Paste the API URL + key into Lucy (the connector runs via npx n8n-mcp).',
      ],
    },
  },

  // ─── connection_string ────────────────────────────────────────────────────
  {
    slug: 'mssql',
    name: 'Microsoft SQL Server (MSSQL)',
    description: 'Query and manage SQL Server, Azure SQL, and Fabric databases.',
    category: 'data',
    icon: '🗄️',
    transport: 'stdio',
    install_ref: 'Azure-Samples/SQL-AI-samples (MssqlMcp) — build from source',
    verified: false,
    config_schema: [
      {
        key: 'CONNECTION_STRING',
        label: 'Connection string',
        type: 'secret',
        required: true,
        help: 'ADO.NET connection string, e.g. Server=host;Database=db;User Id=user;Password=pass;',
      },
    ],
    tools: [
      { name: 'execute_query', description: 'Run a SQL query' },
      { name: 'list_tables', description: 'List tables in the database' },
      { name: 'describe_table', description: 'Describe table schema' },
    ],
    meta: {
      authMethod: 'connection_string',
      docsUrl: 'https://github.com/Azure-Samples/SQL-AI-samples/tree/main/MssqlMcp',
      getKeyUrl: 'https://learn.microsoft.com/en-us/sql/connect/ado-net/connection-string-syntax',
      steps: [
        'Clone Azure-Samples/SQL-AI-samples and open the MssqlMcp folder; pick the dotnet or Node implementation.',
        'Build it: for .NET run \'dotnet build\' in MssqlMcp/dotnet; for Node run \'npm install && npm run build\' in MssqlMcp/Node.',
        'Set the credential: for .NET set CONNECTION_STRING to a standard ADO.NET connection string (SQL auth with User Id/Password, or Entra ID with Authentication=Active Directory Default/Interactive); for Node set SERVER_NAME, DATABASE_NAME, and optionally READONLY=true and TRUST_SERVER_CERTIFICATE=true.',
        'Register the built server in Lucy\'s MCP config (command = dotnet path/to/MssqlMcp.dll, or node path/to/dist/index.js). Optionally set READONLY=true for safer agent access.',
      ],
    },
  },
  {
    slug: 'postgres',
    name: 'Postgres',
    description: 'Query any Postgres database (read-only).',
    category: 'data',
    icon: '🐘',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-postgres',
    verified: true,
    config_schema: [
      {
        key: 'DATABASE_URL',
        label: 'Connection string',
        type: 'secret',
        required: true,
        help: 'postgres://user:pass@host/db',
      },
    ],
    tools: [
      { name: 'query', description: 'Run a read-only SQL query' },
    ],
    meta: {
      authMethod: 'connection_string',
      docsUrl: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres',
      steps: [
        'Get (or build) your Postgres connection string: postgresql://USER:PASSWORD@HOST:PORT/DATABASE.',
        'For a hosted DB, copy the connection URI from your provider\'s dashboard (Supabase/Neon/RDS).',
        'Prefer a dedicated read-only role and add ?sslmode=require for remote databases.',
        'Paste the full URI into Lucy as DATABASE_URL (or pass it as the server\'s CLI argument).',
      ],
    },
  },
  {
    slug: 'redis',
    name: 'Redis',
    description: 'Read/write keys in a Redis store.',
    category: 'data',
    icon: '🟥',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-redis',
    verified: true,
    config_schema: [
      {
        key: 'REDIS_URL',
        label: 'Connection string',
        type: 'secret',
        required: true,
        help: 'redis://user:pass@host:6379',
      },
    ],
    tools: [
      { name: 'get', description: 'Get a key' },
      { name: 'set', description: 'Set a key' },
      { name: 'list', description: 'List keys' },
    ],
    meta: {
      authMethod: 'connection_string',
      docsUrl: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/redis',
      steps: [
        'Get your Redis connection URL: redis://[user:password@]host:port (use rediss:// for TLS).',
        'For a managed Redis (Redis Cloud, Upstash, etc.), copy the connection URL from the provider dashboard.',
        'For local Redis the default is redis://localhost:6379.',
        'Paste the URL into Lucy as REDIS_URL (or pass it as the server\'s CLI argument).',
      ],
    },
  },
  {
    slug: 'mongodb',
    name: 'MongoDB',
    description: 'Query collections and documents.',
    category: 'data',
    icon: '🍃',
    transport: 'stdio',
    install_ref: 'mongodb-mcp-server',
    verified: true,
    config_schema: [
      {
        key: 'MDB_MCP_CONNECTION_STRING',
        label: 'Connection string',
        type: 'secret',
        required: true,
        help: 'mongodb+srv://…',
      },
    ],
    tools: [
      { name: 'find', description: 'Query a collection' },
      { name: 'aggregate', description: 'Run an aggregation' },
    ],
    meta: {
      authMethod: 'connection_string',
      docsUrl: 'https://www.mongodb.com/docs/mcp-server/get-started/',
      steps: [
        'Get your MongoDB connection string (e.g. mongodb+srv://USER:PASSWORD@cluster.mongodb.net/db?retryWrites=true&w=majority).',
        'In MongoDB Atlas go to your cluster > Connect > Drivers to copy the SRV connection string and create/choose a database user.',
        'Add the host running Lucy to the Atlas Network Access IP allowlist.',
        'Paste the connection string into Lucy as MDB_MCP_CONNECTION_STRING.',
      ],
    },
  },

  // ─── builtin / none ───────────────────────────────────────────────────────
  {
    slug: 'filesystem',
    name: 'Filesystem',
    description: 'Read/write local files in an allowed directory.',
    category: 'local',
    icon: '📁',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-filesystem',
    verified: true,
    config_schema: [
      {
        key: 'ALLOWED_DIR',
        label: 'Allowed directory path',
        type: 'text',
        required: true,
        help: 'Absolute path the server may access.',
      },
    ],
    tools: [
      { name: 'read_file', description: 'Read a file' },
      { name: 'write_file', description: 'Write a file' },
      { name: 'list_directory', description: 'List a directory' },
    ],
    meta: {
      authMethod: 'none',
      docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem',
      steps: [
        'No credential needed — the operator configures which directories the server may access.',
        'Register the server in Lucy\'s MCP config: npx -y @modelcontextprotocol/server-filesystem /path/to/allowed/dir.',
        'Pass one or more allowed root directories as arguments to scope access.',
        'Lucy can then read/write/search files within those roots only.',
      ],
    },
  },
  {
    slug: 'fetch',
    name: 'Fetch',
    description: 'Fetch and read web pages / HTTP APIs.',
    category: 'search',
    icon: '🌐',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-fetch',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'fetch', description: 'Fetch a URL as markdown' },
    ],
    meta: {
      authMethod: 'none',
      docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/fetch',
      steps: [
        'No credential needed.',
        'Register the server in Lucy\'s MCP config: npx -y @modelcontextprotocol/server-fetch (or the Python uvx mcp-server-fetch).',
        'Optionally set a custom user-agent or proxy via the server\'s CLI flags.',
        'Lucy can then fetch a URL and receive cleaned Markdown content.',
      ],
    },
  },
  {
    slug: 'sequential-thinking',
    name: 'Sequential Thinking',
    description: 'A structured step-by-step reasoning tool for the AI.',
    category: 'productivity',
    icon: '🧩',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-sequential-thinking',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'sequentialthinking', description: 'Think through a problem step by step' },
    ],
    meta: {
      authMethod: 'none',
      docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking',
      steps: [
        'No credential needed.',
        'Register the server in Lucy\'s MCP config: npx -y @modelcontextprotocol/server-sequential-thinking.',
        'No further configuration required.',
        'Lucy can then use the sequential-thinking tool to break problems into ordered steps.',
      ],
    },
  },
  {
    slug: 'memory',
    name: 'Memory (Knowledge Graph)',
    description: 'A persistent knowledge graph the AI can read and update.',
    category: 'productivity',
    icon: '🧠',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-memory',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'create_entities', description: 'Add entities' },
      { name: 'search_nodes', description: 'Search the graph' },
    ],
    meta: {
      authMethod: 'none',
      docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/memory',
      steps: [
        'No credential needed.',
        'Register the server in Lucy\'s MCP config: npx -y @modelcontextprotocol/server-memory.',
        'Optionally set MEMORY_FILE_PATH to control where the knowledge graph is persisted.',
        'Lucy can then store and retrieve entities/relations across sessions.',
      ],
    },
  },
  {
    slug: 'puppeteer',
    name: 'Puppeteer',
    description: 'Drive a headless browser — navigate, click, screenshot.',
    category: 'local',
    icon: '🎭',
    transport: 'stdio',
    install_ref: '@modelcontextprotocol/server-puppeteer',
    verified: true,
    config_schema: [],
    tools: [
      { name: 'puppeteer_navigate', description: 'Open a URL' },
      { name: 'puppeteer_screenshot', description: 'Take a screenshot' },
    ],
    meta: {
      authMethod: 'none',
      docsUrl: 'https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer',
      steps: [
        'No credential needed.',
        'Register the server in Lucy\'s MCP config: npx -y @modelcontextprotocol/server-puppeteer.',
        'Optionally pass Puppeteer launch options (headless, executable path) via env/config.',
        'Lucy can then drive a headless browser to navigate, interact and screenshot.',
      ],
    },
  },
  {
    slug: 'contractors-room',
    name: 'Contractors Room',
    description: 'Your CTR projects, contracts, and messages.',
    category: 'builtin',
    icon: '🏗️',
    transport: 'http',
    built_in: true,
    verified: true,
    config_schema: [],
    tools: [
      { name: 'list_projects', description: 'List projects' },
      { name: 'send_message', description: 'Send a message' },
    ],
    meta: {
      authMethod: 'none',
      steps: [
        'No external credential needed — this is Lucy\'s first-party built-in connector.',
        'Enable Contractors Room from Lucy\'s /connectors page.',
        'Lucy authenticates the user against the shared Contractors Room backend using the existing session.',
        'Lucy can then query and act on contractor/vendor records, timesheets, invoices and approvals.',
      ],
    },
  },

  // ─── added 2026-06-30: Twenty CRM, ClickUp, Shopify, Dropbox, SSH, Reddit, Facebook ───
  {
    slug: 'twenty-crm',
    name: 'Twenty CRM',
    description: 'Read & write people, companies, tasks, notes in self-hosted Twenty.',
    category: 'crm',
    icon: '🤝',
    transport: 'stdio',
    install_ref: 'npx -y twenty-crm-mcp-server',
    verified: true,
    config_schema: [
      { key: 'TWENTY_API_KEY', label: 'Twenty API Key', type: 'secret', required: true, help: 'Generate under Settings > APIs & Webhooks in your Twenty workspace.' },
      { key: 'TWENTY_BASE_URL', label: 'Twenty Base URL', type: 'text', required: false, help: 'Your self-hosted Twenty URL (e.g. https://crm.example.com). Defaults to https://api.twenty.com.' },
    ],
    tools: [
      { name: 'list_people', description: 'List or filter person records' },
      { name: 'create_company', description: 'Create a company record' },
      { name: 'search_records', description: 'Search across CRM objects' },
      { name: 'create_note', description: 'Create a note' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://docs.twenty.com/developers/extend/api',
      getKeyUrl: 'https://docs.twenty.com/developers',
      steps: [
        'Open your Twenty workspace and go to Settings > APIs & Webhooks (under Developers)',
        'Click Generate API Key and copy the token (shown once)',
        'Paste it into Lucy as TWENTY_API_KEY',
        'Set TWENTY_BASE_URL to your self-hosted instance, e.g. https://crm.example.com (defaults to https://api.twenty.com for Twenty Cloud)',
      ],
    },
  },
  {
    slug: 'clickup',
    name: 'ClickUp',
    description: 'Manage tasks, lists, docs & time tracking in ClickUp.',
    category: 'productivity',
    icon: '✅',
    transport: 'stdio',
    install_ref: 'npx -y @taazkareem/clickup-mcp-server@latest',
    verified: true,
    config_schema: [
      { key: 'CLICKUP_API_KEY', label: 'ClickUp Personal API Token', type: 'secret', required: true, help: 'Generate under Settings > Apps at app.clickup.com/settings/apps.' },
      { key: 'CLICKUP_TEAM_ID', label: 'Workspace (Team) ID', type: 'text', required: true, help: 'The first number in your ClickUp URL after app.clickup.com/.' },
    ],
    tools: [
      { name: 'create_task', description: 'Create a task in a list' },
      { name: 'get_tasks', description: 'List or filter tasks' },
      { name: 'create_list', description: 'Create a list to hold tasks' },
      { name: 'start_time_entry', description: 'Start time tracking on a task' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://github.com/taazkareem/clickup-mcp-server',
      getKeyUrl: 'https://app.clickup.com/settings/apps',
      steps: [
        'Log into ClickUp, go to app.clickup.com/settings/apps, and click Generate (or copy) under API Token',
        'Find your Workspace (Team) ID: it\'s the first number in your ClickUp URL after app.clickup.com/',
        'Paste the token as CLICKUP_API_KEY and the workspace id as CLICKUP_TEAM_ID into Lucy',
        'Lucy runs npx -y @taazkareem/clickup-mcp-server@latest to connect',
      ],
    },
  },
  {
    slug: 'shopify',
    name: 'Shopify',
    description: 'Manage store products, orders, customers & inventory via Admin API.',
    category: 'data',
    icon: '🛍️',
    transport: 'stdio',
    install_ref: 'npx -y shopify-mcp',
    verified: true,
    config_schema: [
      { key: 'MYSHOPIFY_DOMAIN', label: 'Store domain', type: 'text', required: true, help: 'Your myshopify.com domain, e.g. your-store.myshopify.com.' },
      { key: 'SHOPIFY_ACCESS_TOKEN', label: 'Admin API access token', type: 'secret', required: true, help: 'Custom-app Admin API token (shpat_...) from Settings > Apps > Develop apps.' },
    ],
    tools: [
      { name: 'get-products', description: 'List or search products and variants' },
      { name: 'create-product', description: 'Create a new product' },
      { name: 'get-orders', description: 'List and look up orders' },
      { name: 'get-customers', description: 'List and search customers' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/generate-app-access-tokens-admin',
      getKeyUrl: 'https://www.shopify.com/admin/settings/apps/development',
      steps: [
        'In Shopify admin go to Settings > Apps and sales channels > Develop apps (shopify.com/admin/settings/apps/development) and create an app',
        'Under Configuration, grant Admin API scopes for products, orders, customers and inventory (read/write)',
        'Install the app, then copy the Admin API access token (starts with shpat_)',
        'Paste it as SHOPIFY_ACCESS_TOKEN and set MYSHOPIFY_DOMAIN to your-store.myshopify.com',
      ],
    },
  },
  {
    slug: 'dropbox',
    name: 'Dropbox',
    description: 'List, search, upload & download files and folders in Dropbox.',
    category: 'cloud',
    icon: '📦',
    transport: 'stdio',
    install_ref: 'npx -y @microagents/mcp-server-dropbox',
    verified: false,
    config_schema: [
      { key: 'DROPBOX_ACCESS_TOKEN', label: 'Dropbox Access Token', type: 'secret', required: true, help: 'Generate a token in your app\'s Settings tab at dropbox.com/developers/apps. Note: generated tokens are short-lived and must be regenerated when they expire.' },
    ],
    tools: [
      { name: 'list_folder', description: 'List contents of a folder' },
      { name: 'search', description: 'Search for files and folders' },
      { name: 'upload_file', description: 'Upload a new file to Dropbox' },
      { name: 'get_file_link', description: 'Get a temporary link to download a file' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://www.npmjs.com/package/@microagents/mcp-server-dropbox',
      getKeyUrl: 'https://www.dropbox.com/developers/apps',
      steps: [
        'Go to dropbox.com/developers/apps and Create app (Scoped access, choose Full Dropbox or App folder)',
        'On the app\'s Permissions tab enable files.metadata.read, files.content.read and files.content.write, then Submit',
        'On the Settings tab, under OAuth2 > Generated access token, click Generate',
        'Copy the token and paste it into Lucy as DROPBOX_ACCESS_TOKEN',
      ],
    },
  },
  {
    slug: 'ssh',
    name: 'SSH (Linux)',
    description: 'Run shell commands and transfer files on a remote Linux server via SSH.',
    category: 'dev',
    icon: '🖥️',
    transport: 'stdio',
    install_ref: 'npx -y @fangjunjie/ssh-mcp-server',
    verified: true,
    config_schema: [
      { key: 'SSH_HOST', label: 'Host / IP', type: 'text', required: true, help: 'Remote Linux server address, e.g. 203.0.113.10 or server.example.com.' },
      { key: 'SSH_PORT', label: 'Port', type: 'text', required: false, help: 'SSH port. Defaults to 22.' },
      { key: 'SSH_USERNAME', label: 'Username', type: 'text', required: true, help: 'SSH login user, e.g. root or ubuntu.' },
      { key: 'SSH_PASSWORD', label: 'Password', type: 'secret', required: false, help: 'SSH password. Provide this OR a private key.' },
      { key: 'SSH_PRIVATE_KEY', label: 'SSH Private Key', type: 'secret', required: false, help: 'Private key contents (or path). Use instead of a password.' },
      { key: 'SSH_PASSPHRASE', label: 'Key Passphrase', type: 'secret', required: false, help: 'Passphrase protecting the private key, if any.' },
    ],
    tools: [
      { name: 'execute-command', description: 'Run a shell command on the remote server and return output' },
      { name: 'upload', description: 'Upload a local file to the remote server via SFTP' },
      { name: 'download', description: 'Download a file from the remote server via SFTP' },
      { name: 'list-servers', description: 'List configured SSH server connections' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://github.com/classfang/ssh-mcp-server',
      steps: [
        'Have your Linux server SSH details ready: host/IP, port (default 22), and username',
        'Pick auth: an SSH private key (paste the key file contents or its path) OR a password',
        'Server runs via npx -y @fangjunjie/ssh-mcp-server passing --host/--port/--username plus --password or --privateKey (see github.com/classfang/ssh-mcp-server)',
        'Paste the values into Lucy and connect; optionally set a command whitelist for safety',
      ],
    },
  },
  {
    slug: 'reddit',
    name: 'Reddit',
    description: 'Browse & search subreddits, posts, comments; read user info.',
    category: 'search',
    icon: '👽',
    transport: 'stdio',
    install_ref: 'npx -y reddit-mcp-server',
    verified: true,
    config_schema: [
      { key: 'REDDIT_CLIENT_ID', label: 'Reddit Client ID', type: 'text', required: true, help: 'Shown under the app name on reddit.com/prefs/apps after creating a \'script\' app.' },
      { key: 'REDDIT_CLIENT_SECRET', label: 'Reddit Client Secret', type: 'secret', required: true, help: 'The \'secret\' value of your Reddit script app.' },
      { key: 'REDDIT_USERNAME', label: 'Reddit Username', type: 'text', required: false, help: 'Only needed for write actions (posting/commenting); the account the script app uses.' },
      { key: 'REDDIT_PASSWORD', label: 'Reddit Password', type: 'secret', required: false, help: 'Password for the account above; only needed for write actions.' },
    ],
    tools: [
      { name: 'browse_subreddit', description: 'List hot/new/top posts from a subreddit' },
      { name: 'search_reddit', description: 'Search posts across Reddit or within a subreddit' },
      { name: 'get_reddit_post', description: 'Fetch a post with its comments' },
      { name: 'get_user_info', description: 'Get a Reddit user\'s profile and activity' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://github.com/jordanburke/reddit-mcp-server',
      getKeyUrl: 'https://www.reddit.com/prefs/apps',
      steps: [
        'Go to reddit.com/prefs/apps and click \'create another app\', choosing the \'script\' type',
        'Copy the client id (under the app name) and the \'secret\' value',
        'For write actions, also note the Reddit account username + password the script app runs as',
        'Paste REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET (and optionally username/password) into Lucy',
      ],
    },
  },
  {
    slug: 'facebook',
    name: 'Facebook',
    description: 'Manage Facebook Pages: publish posts, read comments, page insights.',
    category: 'messaging',
    icon: '📘',
    transport: 'stdio',
    install_ref: 'npx -y @node2flow/facebook-pages-mcp',
    verified: true,
    config_schema: [
      { key: 'FACEBOOK_PAGE_ACCESS_TOKEN', label: 'Page Access Token', type: 'secret', required: true, help: 'Long-lived Page token from the Graph API Explorer at developers.facebook.com/tools/explorer/.' },
      { key: 'FACEBOOK_PAGE_ID', label: 'Page ID', type: 'text', required: false, help: 'Your Facebook Page ID. Optional; auto-detected from the token if omitted.' },
    ],
    tools: [
      { name: 'fb_create_post', description: 'Publish a post to the Page' },
      { name: 'fb_list_comments', description: 'Read comments on a post' },
      { name: 'fb_create_comment', description: 'Reply to a comment as the Page' },
      { name: 'fb_get_page_insights', description: 'Fetch Page analytics/insights' },
    ],
    meta: {
      authMethod: 'api_key',
      docsUrl: 'https://developers.facebook.com/docs/pages-api/',
      getKeyUrl: 'https://developers.facebook.com/tools/explorer/',
      steps: [
        'Create/select an app at developers.facebook.com and open the Graph API Explorer at developers.facebook.com/tools/explorer/',
        'Choose your Page, click Get Page Access Token, and grant pages_manage_posts, pages_read_engagement, and pages_read_user_content',
        'Exchange it for a long-lived (60-day) or never-expiring Page token and copy your Page ID',
        'Paste the token as FACEBOOK_PAGE_ACCESS_TOKEN (and optionally FACEBOOK_PAGE_ID) into Lucy',
      ],
    },
  },
];

/** Idempotent upsert of the catalog into lucy.mcp_servers (service-role client). */
export async function seedCatalog(svc: SupabaseClient<any, any, any>): Promise<void> {
  for (const s of CATALOG) {
    await svc.from('mcp_servers').upsert({
      slug: s.slug, name: s.name, description: s.description, author: s.author ?? null,
      category: s.category, icon: s.icon ?? null, transport: s.transport, install_ref: s.install_ref ?? null,
      config_schema: s.config_schema, tools: s.tools, verified: s.verified ?? false, built_in: s.built_in ?? false,
      meta: s.meta ?? {},
    }, { onConflict: 'slug' });
  }
}
